# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANoJVMtXCwoo3u3TXtnAKmcBFKJbTTEu
"""

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForCausalLM

ENCODER_PATH = "outputs/encoder_model"
DECODER_PATH = "outputs/decoder_model"
ID2LABEL = {0: "Facturación", 1: "Problema Técnico", 2: "Baja del Servicio", 3: "Información Comercial"}
RESPUESTA_AUTOMATICA_PARA = {"Información Comercial", "Problema Técnico"}
device = "cuda" if torch.cuda.is_available() else "cpu"

enc_tok = AutoTokenizer.from_pretrained (ENCODER_PATH)
enc_mod = AutoModelForSequenceClassification.from_pretrained (ENCODER_PATH).to (device).eval()
dec_tok = AutoTokenizer.from_pretrained (DECODER_PATH)
dec_tok.pad_token = dec_tok.eos_token
dec_mod = AutoModelForCausalLM.from_pretrained (DECODER_PATH).to (device).eval()
print ("Modelos Cargados")

def clasificar (text):
    inputs = enc_tok (text, return_tensors = "pt", truncation = True, padding = True, max_length = 64)
    inputs = {k: v.to (device) for k, v in inputs.items()}
    with torch.no_grad():
        logits = enc_mod (**inputs).logits
    return ID2LABEL [logits.argmax (-1).item()]

def generar (text):
    prompt = f"### Ticket de Soporte:\n{text}\n\n### Respuesta del Agente:\n"
    inputs = dec_tok (prompt, return_tensors = "pt").to (device)
    with torch.no_grad():
        out = dec_mod.generate (**inputs, max_new_tokens = 100, do_sample = True,
                                temperature = 0.7, top_p = 0.9, pad_token_id = dec_tok.eos_token_id)
    resp = dec_tok.decode (out [0][inputs ["input_ids"].shape [1]:], skip_special_tokens = True)
    return resp.split ("##") [0].strip()

tickets = [
    "¿Cuánto cuesta el paquete de fibra más móvil para dos personas?",
    "Llevo dos días sin internet. He reiniciado el router varias veces.",
    "Quiero darme de baja de todos los servicios.",
]

for t in tickets:
    cat = clasificar (t)
    print (f"\n📩 {t}")
    print (f"🔖 {cat}")
    if cat in RESPUESTA_AUTOMATICA_PARA:
        print (f"💬 {generar(t)}")
    else:
        print (f"💬 [Derivado — Sin Respuesta Automática]")