# -*- coding: utf-8 -*-
"""encoder_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANoJVMtXCwoo3u3TXtnAKmcBFKJbTTEu
"""

"""
Tarea: Clasificación de Tickets de Soporte
Modelo Base: dccuchile/bert-base-spanish-wwm-uncased
Clases: Facturación | Problema Técnico | Baja del Servicio | Información Comercial

Ejecuta primero 'create_dataset.py' para generar los CSVs.
"""

# ══════════════════════════════════════════════
# CELDA 01 — Instalación de Dependencias
# ══════════════════════════════════════════════
!pip install transformers datasets scikit-learn matplotlib seaborn torch --quiet

# ══════════════════════════════════════════════
# CELDA 02 — Imports
# ══════════════════════════════════════════════
import csv
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    accuracy_score,
)

SEED = 42
random.seed (SEED)
np.random.seed (SEED)
torch.manual_seed (SEED)

LABEL2ID = {
    "Facturación": 0,
    "Problema Técnico": 1,
    "Baja del Servicio": 2,
    "Información Comercial": 3,
}

ID2LABEL = {v: k for k, v in LABEL2ID.items()}
NUM_LABELS = len (LABEL2ID)

print ("Imports OK")
print (f"GPU Disponible: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print (f"GPU: {torch.cuda.get_device_name (0)}")

# ══════════════════════════════════════════════
# CELDA 03 — Cargar Datos
# ══════════════════════════════════════════════
def load_csv (path):
    with open (path, encoding = "utf-8") as f:
        reader = csv.DictReader (f)
        return list (reader)

train_raw = load_csv ("data/tickets_train.csv")
test_raw = load_csv ("data/tickets_test.csv")

train_texts = [r ["text"]  for r in train_raw]
train_labels = [LABEL2ID [r ["label"]] for r in train_raw]
test_texts = [r ["text"]  for r in test_raw]
test_labels = [LABEL2ID [r ["label"]] for r in test_raw]

print (f"Datos Cargados: {len (train_texts)} Train / {len (test_texts)} Test")

# ══════════════════════════════════════════════
# CELDA 04 — EDA: Distribución de Clases
# ══════════════════════════════════════════════
from collections import Counter

train_counts = Counter (r ["label"] for r in train_raw)
labels_sorted = sorted (train_counts.keys())
counts_sorted = [train_counts [l] for l in labels_sorted]

fig, ax = plt.subplots (figsize = (9, 5))
bars = ax.bar (labels_sorted, counts_sorted,
               color = ["#4C72B0", "#DD8452", "#55A868", "#C44E52"], edgecolor = "black")
ax.set_title ("Distribución de Clases en el Conjunto de Entrenamiento", fontsize = 14)
ax.set_xlabel ("Categoría del Ticket", fontsize = 12)
ax.set_ylabel ("Número de Ejemplos", fontsize = 12)
for bar, count in zip (bars, counts_sorted):
    ax.text (bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
             str (count), ha = "center", va = "bottom", fontsize = 12)
plt.tight_layout()
os.makedirs ("outputs", exist_ok = True)
plt.savefig ("outputs/class_distribution.png", dpi = 150)
plt.show()
print ("Gráfico Guardado en 'outputs/class_distribution.png'")

# ══════════════════════════════════════════════
# CELDA 05 — EDA: Histograma de Longitudes de Texto
# ══════════════════════════════════════════════
all_lengths = [len (t.split()) for t in train_texts + test_texts]

fig, ax = plt.subplots (figsize = (8, 4))
ax.hist (all_lengths, bins = 20, color = "#4C72B0", edgecolor = "black")
ax.axvline (np.percentile (all_lengths, 75), color = "red", linestyle = "--",
            label = f"P75 = {int (np.percentile (all_lengths, 75))} Palabras")
ax.axvline (np.percentile (all_lengths, 95), color = "orange", linestyle = "--",
            label = f"P95 = {int (np.percentile (all_lengths, 95))} Palabras")
ax.set_title ("Distribución de Longitudes de Ticket (en Palabras)", fontsize = 14)
ax.set_xlabel ("Número de Palabras", fontsize = 12)
ax.set_ylabel ("Frecuencia", fontsize = 12)
ax.legend()
plt.tight_layout()
plt.savefig ("outputs/length_distribution.png", dpi = 150)
plt.show()

print (f"Longitud Media: {np.mean(all_lengths):.1f} Palabras")
print (f"Longitud Máxima: {max(all_lengths)} Palabras")
print (f"P75: {int (np.percentile (all_lengths, 75))} Palabras → Elegimos max_length = 64")
print ("Gráfico Guardado en 'outputs/length_distribution.png'")

# ══════════════════════════════════════════════
# CELDA 06 — Tokenización
# ══════════════════════════════════════════════
MODEL_NAME = "dccuchile/bert-base-spanish-wwm-uncased"
MAX_LENGTH = 64  # Justificado por el Histograma: P95 < 50 palabras

tokenizer = AutoTokenizer.from_pretrained (MODEL_NAME)

class TicketDataset (Dataset):
    def __init__ (self, texts, labels):
        self.encodings = tokenizer (
            texts,
            truncation = True,
            padding = "max_length",
            max_length = MAX_LENGTH,
            return_tensors = "pt",
        )

        self.labels = labels

    def __len__ (self):
        return len (self.labels)

    def __getitem__ (self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item ["labels"] = torch.tensor (self.labels [idx])
        return item

train_dataset = TicketDataset (train_texts, train_labels)
test_dataset  = TicketDataset (test_texts,  test_labels)
print (f"Tokenización Completa. max_length = {MAX_LENGTH}")

# ══════════════════════════════════════════════
# CELDA 07 — Modelo y Métricas
# ══════════════════════════════════════════════
model = AutoModelForSequenceClassification.from_pretrained (
    MODEL_NAME,
    num_labels = NUM_LABELS,
    id2label = ID2LABEL,
    label2id = LABEL2ID,
)

print (f"Modelo Cargado: {MODEL_NAME}")

def compute_metrics (eval_pred):
    logits, labels = eval_pred
    preds = np.argmax (logits, axis = -1)
    f1  = f1_score (labels, preds, average = "weighted")
    acc = accuracy_score (labels, preds)
    return {"f1": f1, "accuracy": acc}

# ══════════════════════════════════════════════
# CELDA 08 — Entrenamiento
# ══════════════════════════════════════════════
training_args = TrainingArguments (
    output_dir = "outputs/encoder_checkpoints",
    num_train_epochs = 5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    warmup_steps = 20,
    weight_decay = 0.01,
    learning_rate = 2e-5,
    eval_strategy = "epoch",
    save_strategy = "epoch",
    load_best_model_at_end = True,
    metric_for_best_model = "f1",
    logging_dir = "outputs/logs",
    logging_steps = 10,
    report_to = "none",
    seed = SEED,
)

trainer = Trainer (
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = test_dataset,
    compute_metrics = compute_metrics,
    callbacks = [EarlyStoppingCallback (early_stopping_patience = 2)],
)

print ("Iniciando Entrenamiento...")
trainer.train()
print ("Entrenamiento Completado.")

# ══════════════════════════════════════════════
# CELDA 09 — Evaluación en Test
# ══════════════════════════════════════════════
predictions = trainer.predict (test_dataset)
preds = np.argmax (predictions.predictions, axis = -1)
true_labels = [t ["labels"].item() for t in test_dataset]

print ("\n" + "=" * 60)
print ("RESULTADOS EN TEST")
print ("=" * 60)
print (classification_report (
       true_labels, preds,
       target_names = list (LABEL2ID.keys())
))

f1_final = f1_score (true_labels, preds, average = "weighted")
acc_final = accuracy_score (true_labels, preds)
print (f"F1 (weighted): {f1_final:.4f}")
print (f"Accuracy: {acc_final:.4f}")

# ══════════════════════════════════════════════
# CELDA 10 — Matriz de Confusión
# ══════════════════════════════════════════════
cm = confusion_matrix (true_labels, preds)
label_names = list (LABEL2ID.keys())

fig, ax = plt.subplots (figsize = (8, 6))
sns.heatmap (cm, annot=True, fmt="d", cmap="Blues",
             xticklabels = label_names, yticklabels = label_names,
             ax = ax, linewidths = 0.5)
ax.set_xlabel ("Predicción", fontsize = 12)
ax.set_ylabel ("Etiqueta real", fontsize = 12)
ax.set_title (f"Matriz de Confusión — F1 = {f1_final:.4f}", fontsize = 14)
plt.xticks (rotation = 30, ha = "right")
plt.tight_layout()
plt.savefig ("outputs/confusion_matrix.png", dpi = 150)
plt.show()
print ("Matriz Guardada en 'outputs/confusion_matrix.png'")

# ══════════════════════════════════════════════
# CELDA 11 — Guardar Modelo Fine-Tuneado
# ══════════════════════════════════════════════
SAVE_PATH = "outputs/encoder_model"
model.save_pretrained (SAVE_PATH)
tokenizer.save_pretrained (SAVE_PATH)
print (f"Modelo Guardado en 'outputs/encoder_model/'")

# ══════════════════════════════════════════════
# CELDA 12 — Prueba Rápida de Inferencia
# ══════════════════════════════════════════════
def predict_category (text):
    model.eval()
    inputs = tokenizer (text, return_tensors = "pt", truncation = True,
                        padding = True, max_length = MAX_LENGTH)
    inputs = {k: v.to (model.device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model (**inputs)
    pred_id = outputs.logits.argmax (-1).item()
    return ID2LABEL [pred_id]

test_samples = [
    "¿Cuánto cuesta el paquete de fibra más móvil para dos personas?",
    "Llevo dos días sin internet y ya he reiniciado el router varias veces.",
    "Quiero darme de baja de todos los servicios.",
    "En mi última factura hay un cargo que no reconozco.",
]

print ("\nPrueba de Inferencia:")
for sample in test_samples:
    print (f"Texto: {sample [:60]}...")
    print (f"→ Categoría: {predict_category (sample)}\n")