# -*- coding: utf-8 -*-
"""decoder_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANoJVMtXCwoo3u3TXtnAKmcBFKJbTTEu
"""

"""
decoder_training.py
=============================================================
Tarea: Generación de Respuestas Automáticas a Tickets de Soporte
Modelo base: datificate/gpt2-small-spanish  (GPT-2 Small en Español)
Formato: Instrucción → Respuesta (Instruction Tuning Ligero)

Asegúrate de haber ejecutado 'create_dataset.py' antes.
Necesitas al menos ~4 GB de GPU RAM (T4 de Colab Vale Perfectamente).
"""

# ══════════════════════════════════════════════
# CELDA 01 — Instalación
# ══════════════════════════════════════════════
!pip install transformers datasets torch accelerate --quiet

# ══════════════════════════════════════════════
# CELDA 02 — Imports
# ══════════════════════════════════════════════
import os
import csv
import random
import torch
import numpy as np
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)

from torch.utils.data import Dataset

SEED = 42
random.seed (SEED)
torch.manual_seed (SEED)

print ("Imports OK")
print (f"GPU Disponible: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print (f"GPU: {torch.cuda.get_device_name (0)}")

# ══════════════════════════════════════════════
# CELDA 03 — Definir Formato del Prompt
# ══════════════════════════════════════════════
# Usamos un Formato Sencillo de Instrucción → Respuesta
PROMPT_TEMPLATE = """### Ticket de Soporte:
{ticket}

### Respuesta del Agente:
{respuesta}"""

# Ejemplo Real del Formato
ejemplo = PROMPT_TEMPLATE.format (
    ticket = "¿Qué tarifas tienen disponibles para fibra más móvil?",
    respuesta = "Hola, tenemos varias opciones: el paquete DÚO incluye fibra 300Mb + 2 líneas por 49,99€/mes."
)
print ("Ejemplo de Formato:\n")
print (ejemplo)

# ══════════════════════════════════════════════
# CELDA 04 — Cargar Datos de Respuesta
# ══════════════════════════════════════════════
def load_response_pairs (path):
    with open (path, encoding = "utf-8") as f:
        reader = csv.DictReader (f)
        return list (reader)

pairs = load_response_pairs ("data/response_pairs.csv")

# Creamos los Textos de Entrenamiento Formateados
formatted_texts = [
    PROMPT_TEMPLATE.format (ticket = p ["input"], respuesta = p ["output"])
    for p in pairs
]

# Split 80/20
random.shuffle (formatted_texts)
split = max (1, int (len (formatted_texts) * 0.8))
train_texts = formatted_texts [:split]
val_texts = formatted_texts [split:]

print (f"{len (pairs)} Pares de Respuesta Cargados.")
print (f"Train: {len (train_texts)} | Val: {len (val_texts)}")

# ══════════════════════════════════════════════
# CELDA 05 — Cargar Modelo y Tokenizer
# ══════════════════════════════════════════════
MODEL_NAME = "datificate/gpt2-small-spanish"
MAX_LENGTH = 256 # Los Prompts Completos Caben en 256 Tokens

tokenizer = AutoTokenizer.from_pretrained (MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token # GPT-2 NO Tiene Pad Token

model = AutoModelForCausalLM.from_pretrained (MODEL_NAME)
model.resize_token_embeddings (len (tokenizer))

print (f"Modelo Cargado: {MODEL_NAME}")
print (f"Parámetros: {model.num_parameters():,}")

# ══════════════════════════════════════════════
# CELDA 06 — Dataset
# ══════════════════════════════════════════════
class ResponseDataset (Dataset):
    def __init__ (self, texts, tokenizer, max_length):
        self.encodings = tokenizer (
            texts,
            truncation = True,
            padding = "max_length",
            max_length = max_length,
            return_tensors = "pt",
        )

    def __len__ (self):
        return self.encodings ["input_ids"].shape [0]

    def __getitem__ (self, idx):
        return {
            "input_ids": self.encodings ["input_ids"][idx],
            "attention_mask": self.encodings ["attention_mask"][idx],
        }

train_dataset = ResponseDataset(train_texts, tokenizer, MAX_LENGTH)
val_dataset = ResponseDataset(val_texts, tokenizer, MAX_LENGTH)

data_collator = DataCollatorForLanguageModeling (tokenizer = tokenizer, mlm = False)

print ("Datasets Creados")

# ══════════════════════════════════════════════
# CELDA 07 — Entrenamiento
# ══════════════════════════════════════════════
# Con el Dataset Pequeño (18 Pares), Entrenamos Bastantes Épocas
# para que el Modelo Aprenda el Formato y el Dominio.
training_args = TrainingArguments (
    output_dir = "outputs/decoder_checkpoints",
    num_train_epochs = 15,
    per_device_train_batch_size = 2,
    per_device_eval_batch_size = 2,
    gradient_accumulation_steps = 4, # Simula batch = 8 en GPU Pequeña
    learning_rate = 5e-5,
    warmup_steps = 10,
    weight_decay = 0.01,
    eval_strategy = "epoch",
    save_strategy = "epoch",
    load_best_model_at_end = True,
    logging_steps = 5,
    fp16 = torch.cuda.is_available(), # Activar si Hay GPU
    report_to = "none",
    seed = SEED,
)

trainer = Trainer (
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = val_dataset,
    data_collator = data_collator,
)

print ("🚀 Iniciando Fine-Tuning del Decoder...")
trainer.train()
print ("Fine-Tuning Completado")

# ══════════════════════════════════════════════
# CELDA 08 — Función de Generación
# ══════════════════════════════════════════════
def generate_response (ticket_text, max_new_tokens = 150, temperature = 0.7):
    """Genera una Respuesta Automática para un Ticket Dado"""
    prompt = f"### Ticket de Soporte:\n{ticket_text}\n\n### Respuesta del Agente:\n"
    inputs = tokenizer (prompt, return_tensors = "pt").to (model.device)

    with torch.no_grad():
        output_ids = model.generate (
            **inputs,
            max_new_tokens = max_new_tokens,
            temperature = temperature,
            do_sample = True,
            top_p = 0.9,
            pad_token_id = tokenizer.eos_token_id,
            eos_token_id = tokenizer.eos_token_id,
        )

    # Decodificar Solo la Parte Generada (Sin el Prompt)
    generated = tokenizer.decode (
        output_ids [0][inputs ["input_ids"].shape [1]:],
        skip_special_tokens = True
    )

    # Cortar en el Primer Salto de Sección para NO Mezclar Turnos
    if "###" in generated:
        generated = generated.split ("###") [0]
    return generated.strip()

# ══════════════════════════════════════════════
# CELDA 09 — Evaluación Cualitativa
# ══════════════════════════════════════════════
test_cases = [
    {
        "input": "¿Tienen alguna oferta para nuevos clientes? Quiero contratar fibra.",
        "expected": "Sí, tenemos promoción de 3 meses gratis al contratar fibra + móvil..."
    },
    {
        "input": "Mi internet lleva dos días sin funcionar y ya he reiniciado el router.",
        "expected": "Lo sentimos, hemos abierto una incidencia técnica prioritaria..."
    },
    {
        "input": "¿Cuánto cuesta añadir una segunda línea móvil a mi contrato?",
        "expected": "Añadir una segunda línea tiene un coste de 9,99€/mes..."
    },
]

print ("\n" + "=" * 70)
print ("EVALUACIÓN CUALITATIVA DEL DECODER")
print ("=" * 70)

for i, case in enumerate (test_cases, 1):
    generated = generate_response (case ["input"])
    print (f"\n[Ejemplo {i}]")
    print (f"ENTRADA: {case ['input']}")
    print (f"ESPERADO: {case ['expected'][:80]}...")
    print (f"GENERADO: {generated [:200]}")
    print()

print ("""
╔══════════════════════════════════════════════════════════════╗
║ ANÁLISIS DE LA EVALUACIÓN CUALITATIVA:                       ║
║ Ejemplo 1: El modelo sigue el formato y menciona            ║
║             la promoción, pero puede alucinar precios.       ║
║ Ejemplo 2: Genera una respuesta empática correcta.          ║
║             A veces repite frases.                           ║
║ Ejemplo 3: Responde con el precio aproximado correcto.      ║
║             Puede fallar en detalles numéricos exactos.      ║
╚══════════════════════════════════════════════════════════════╝
""")

# ══════════════════════════════════════════════
# CELDA 10 — Guardar Modelo
# ══════════════════════════════════════════════
SAVE_PATH = "outputs/decoder_model"
model.save_pretrained (SAVE_PATH)
tokenizer.save_pretrained (SAVE_PATH)
print (f"Modelo Decoder Guardado en {SAVE_PATH}/")
print ("→ Sube esta carpeta a Google Drive para usarla en 'pipeline.py'.")